# Dockerfile
FROM nvcr.io/nvidia/l4t-jetpack:r36.4.0

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    TRANSFORMERS_CACHE=/workspace/.hf \
    HF_HOME=/workspace/.hf \
    HF_ENDPOINT=https://hf-mirror.com
RUN chmod 1777 /tmp && apt-get update && apt-get install -y \
    curl wget ca-certificates \
    tar \
    &&  update-ca-certificates && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y python3 python3-pip git ffmpeg libglib2.0-0 libsm6 libxrender1 libxext6

# RUN pip3 config set global.index-url https://mirrors.aliyun.com/pypi/simple
# RUN pip3 config set install.trusted-host mirrors.aliyun.com
# RUN pip3 install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu124 \
# RUN pip3 install -U --no-cache-dir transformers FlagEmbedding uvicorn fastapi
RUN wget https://pypi.jetson-ai-lab.io/jp6/cu126/+f/62a/1beee9f2f1470/torch-2.8.0-cp310-cp310-linux_aarch64.whl#sha256=62a1beee9f2f147076a974d2942c90060c12771c94740830327cae705b2595fc && \
    pip install torch-2.8.0-cp310-cp310-linux_aarch64.whl

RUN wget https://pypi.jetson-ai-lab.io/jp6/cu126/+f/907/c4c1933789645/torchvision-0.23.0-cp310-cp310-linux_aarch64.whl#sha256=907c4c1933789645ebb20dd9181d40f8647978e6bd30086ae7b01febb937d2d1 && \
    pip install torchvision-0.23.0-cp310-cp310-linux_aarch64.whl

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && \
    pip config set install.trusted-host mirrors.aliyun.com && \
    pip install --no-cache-dir transformers FlagEmbedding uvicorn fastapi --index-url https://mirrors.aliyun.com/pypi/simple \
    --trusted-host mirrors.aliyun.com/pypi/simple \
    --timeout 120 --retries 5 \
    --upgrade-strategy only-if-needed
    # --break-system-packages


WORKDIR /app
COPY manager/ /app/manager/
COPY worker/ /app/worker/

# 默认启动 Manager
ENV HOST=0.0.0.0 PORT=18000
EXPOSE 18000
CMD ["uvicorn", "manager.app:app", "--host", "0.0.0.0", "--port", "18000"]